/** Hitbox baking shared by scripts/bake.ts and the freshness test. */
import { boneAt, solve } from '../render/figure';
import type { CharacterDef } from '../sim/types';
import { sampleAnim } from './poses';

export function bakeHitpos(chars: Record<string, CharacterDef>): Record<string, [number, number][]> {
  const out: Record<string, [number, number][]> = {};
  for (const [cid, def] of Object.entries(chars)) {
    for (const m of Object.values(def.moves)) {
      m.hitboxes?.forEach((hb, n) => {
        if (!hb.bone || hb.aimed) return;
        const pts: [number, number][] = [];
        for (let f = hb.f0; f <= hb.f1; f++) {
          const pose = sampleAnim(m.anim, f);
          const sp = m.anim.spin;
          const spin = sp && f >= sp.f0 && f <= sp.f1 ? ((f - sp.f0) / Math.max(1, sp.f1 - sp.f0)) * sp.deg : 0;
          const j = solve(def.build, pose, 0, 0, 1, m.where !== 'air', spin, null, 1);
          const b = boneAt(j, hb.bone);
          pts.push([Math.round(b[0]), Math.round(b[1])]);
        }
        out[`${cid}/${m.id}/${n}`] = pts;
      });
    }
  }
  return out;
}

export function renderHitpos(map: Record<string, [number, number][]>): string {
  const keys = Object.keys(map).sort();
  const lines = keys.map((k) => `  '${k}': ${JSON.stringify(map[k])},`);
  return `// Generated by scripts/bake.ts from the move animations. Do not edit.\nexport const HITPOS: Record<string, [number, number][]> = {\n${lines.join('\n')}\n};\n`;
}
